[package]
name = "tough-pkcs11"
version = "0.19.0"
description = "Implements PKCS11 as a key source for TUF signing keys"
authors = []
license = "MIT OR Apache-2.0"
repository = "https://github.com/awslabs/tough"
keywords = ["TUF", "PKCS11"]
edition = "2018"

[dependencies]
aws-lc-rs = "1"
cryptoki = "0.12.0"
p256 = { version = "0.14.0", default-features = false, features = [
    "ecdsa-core",
] }
pem = "3.0.6"
percent-encoding = "2.3.2"
pk11-uri-parser = "0.1.5"
snafu = { version = "0.8", features = ["backtraces-impl-backtrace-crate"] }
tokio = { version = "1.53.0", features = ["rt"] }
tough = { version = "0.24", path = "../tough" }

[dev-dependencies]
secrecy = "0.10.3"
tempfile = "3.27.0"

[features]
# Enable softhsm integration tests
test-softhsm = []
