name: Rust
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/dependabot.yml"
    branches: [develop]
  workflow_dispatch:

env:
  # From-scratch builds with incremental compilation enabled adds unneeded performance and disk overhead.
  CARGO_INCREMENTAL: "0"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        make_target: ["check-licenses", "build", "integ", "integ-fips"]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          - os: windows-latest
            make_target: check-licenses
          - os: macos-latest
            make_target: check-licenses
          - os: macos-latest
            make_target: integ-fips
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: |
            .cargo
          # you can edit the .github/cache_bust file if you need to clear the cache
          key: ${{ hashFiles('.github/cache_bust') }}-${{ runner.os }}-${{ matrix.make_target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ hashFiles('.github/cache_bust') }}-${{ runner.os }}-${{ matrix.make_target }}
      - uses: ilammy/setup-nasm@v1 # requirement for windows FIPS builds
      # print the current rustc. replace stable to pin to a specific toolchain version.
      - run: rustup default stable
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - run: make ${{ matrix.make_target }}
      - name: Install pkcs11-tool and SoftHSM (Linux only)
        if: matrix.os == 'ubuntu-latest' && matrix.make_target == 'integ'
        run: |
          sudo apt-get update
          sudo apt-get install -y opensc softhsm2
      - name: Run PKCS11/SoftHSM integration target (Linux only)
        if: matrix.os == 'ubuntu-latest' && matrix.make_target == 'integ'
        run: make integ-pkcs11-softhsm
